### ISSUE TITLE
UI: Register a company: Fix select language icon position

### ISSUE THREAD

**Issue by kolodgeeva** [Autopartner/autopartner-ui#82]
Expected:
https://vuero.cssninja.io/auth/signup-2

Actual:

![Image](https://github.com/Autopartner/autopartner-ui/assets/2835251/c589ea53-d2be-4d32-85ff-77dfd7e31397)

**Comment by EvgeniyGelfman** [comment]
https://github.com/Autopartner/autopartner-ui/pull/85 fix
